DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
  FUSE: FuseFastToSlow
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 18
  TRANS_FUNC: basic_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[2, 2], [2, 2], [2, 2], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[],[]],[[],[]],[[],[]],[[],[]]]
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  MODEL_NAME: SlowFast
  DROPOUT_RATE: 0.0
