batch_size: 1
config: ./configs/baseline.yaml
dataset: KSL
dataset_info:
  dataset_root: ./dataset/KSL
  dict_path: ./preprocess/KSL/gloss_dict.npy
  evaluation_dir: ./evaluation/slr_eval
  evaluation_prefix: KSL-groundtruth
decode_mode: beam
device: '0'
eval_interval: 1
evaluate_tool: python
feeder: dataset.dataloader_video.BaseFeeder
feeder_args:
  datatype: video
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0
  input_size: 224
  mode: train
  num_gloss: -1
ignore_weights: []
load_checkpoints: null
load_weights: null
log_interval: 10000
loss_weights:
  ConvCTC: 1.0
  Dist: 25.0
  Fast: 0.25
  SeqCTC: 1.0
  Slow: 0.25
model: slr_network_multi.SLRModel
model_args:
  c2d_type: slowfast101
  conv_type: 2
  num_classes: 1296
  share_classifier: 1
  use_bn: 1
  weight_norm: true
num_epoch: 80
num_worker: 4
optimizer_args:
  base_lr: 0.0001
  gamma: 0.2
  learning_ratio: 1
  nesterov: false
  optimizer: Adam
  scheduler: multistep
  start_epoch: 0
  step:
  - 40
  - 60
  weight_decay: 0.0001
phase: train
print_log: true
random_fix: true
random_seed: 0
save_interval: 5
slowfast_args: {}
slowfast_config: SLOWFAST_64x2_R101_50_50.yaml
test_batch_size: 2
work_dir: ./work_dir/KSL/
